### ISSUE TITLE
Can't work correctly in win7 x64

### ISSUE THREAD

**Issue by lstoryc** [loo2k/Sublime-Text-Portable-Tool#2]
I have try to run it in my computer (win7 x64), the dat windows shows fleeting, please help to check it and thanks.

**Comment by Cojad** [comment]
I have no issue to run this tool in Win7x64.
You have to make sure your run it as administrator privilege. Or the tool will fail while writing to registry.

**Comment by Cojad** [comment]
to loo2k, this is not win7x64 issue. This Privilege issue effect on Windows system since Vista introduce UAC.
不管32/64位元系統如果UAC沒有關掉, 都必須要改以Admin權限來執行, 不然都會遇到.

**Comment by loo2k** [comment]
@Cojad Sorry. 原來是我在 32 位系統上關閉了 UAC，所以沒有發現這個問題。以為只有在 64 位系統上才又這個情況。
感謝 :) :+1:

**Comment by Cojad** [comment]
改天重新用vbscript來重寫工具吧...
vbscript可以支援UAC的設定
http://www.kellestine.com/self-elevate-vbscript/
不過要改成vbscript的工程還真有點大..幾乎等於重寫

**Comment by loo2k** [comment]
@Cojad Nice.
