### ISSUE TITLE
为什么没有Sublime Text 3的啊啊啊

### ISSUE THREAD

**Issue by xieranmaya** [loo2k/Sublime-Text-Portable-Tool#3]
rt

**Comment by Cojad** [comment]
這是2/3都可以用的喔

**Comment by xieranmaya** [comment]
好吧，看源代码里只有Sublime Text 2字样，以为只支持2呢，那3的话会在菜单里显示成用3打开吗

**Comment by Cojad** [comment]
依然顯示為2, 判斷版本比較麻煩, 3依然是beta
故目前依然是使用2, 但實際上3的架構改變並未影響這個tool的運作
如果你覺得2看著不習慣就自己fork改成3或是乾脆拿掉吧.

**Comment by xieranmaya** [comment]
我两个版本同时都装了肿么办，默认会选择哪一个呢？

**Comment by Cojad** [comment]
請參考使用說明的第一句話
「将 Sublime-Text-Portable-Tool.bat 和 ext.txt 两个文件复制到 Sublime Text 的文件夹中」
你複製到2的文件夾來執行那就是2的版本, 你複製到3的文件夾執行就是3的版本
重點在工具在哪個資料夾內, 工具本身並沒有選擇的能力, 只有你有.

**Comment by xieranmaya** [comment]
啊，太不好意思了……我还没读Readme就跑去读了源代码了，结果问了一堆无脑问题，原谅我吧~~~

**Comment by loo2k** [comment]
抱歉因为已经很久没用 Win 了，所以也没有及时更新。
刚刚修改了下版本信息，希望不会让其他人误会。
Sublime Text 2/3 均可以正常绑定扩展名和右键菜单 :)
@xieranmaya @Cojad
